### ISSUE TITLE
Converstion of string format timetsamp to datetime

### ISSUE THREAD

**Issue by Madhu1512** [andrewgross/json2parquet#14]
First of all thanks for the nice library.

I am using ingest_data(msg, schema) function to convert my python list to parquet files, but I have a timestamp field which is in string format (%Y-%m-%dT%H: %M: %S. %fZ) which I would like to convert into datetime before I write into parquet file. What is the best way to achieve this conversion?

**Comment by andrewgross** [comment]
Good question.  I don't have a ton of support at the moment for this.  At the moment all datetime parsing is done by the `pandas` library's `to_datetime` function here:

https://github.com/andrewgross/json2parquet/blob/master/json2parquet/client.py#L66

This function does take a `format` argument which would work with your string format.  I will work on adding this as a keyword arg.

**Comment by andrewgross** [comment]
This has been added in `0.0.15`
