### ISSUE TITLE
Missing write_parquet_dataset from release

### ISSUE THREAD

**Issue by mthota15** [andrewgross/json2parquet#19]
I installed 0.0.16 release today, still I am unable import  write_parquet_dataset function.

Python 3.6.4 (default, Mar  1 2018, 18:36:33)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from json2parquet import write_parquet_dataset
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'write_parquet_dataset'
>>>

#17

**Comment by andrewgross** [comment]
Woops, forgot to bring it in to the top level import.  Fixed in `0.0.17`.  If you are stuck on `0.0.16` you can import it with `from json2parquet.client import write_parquet_dataset`
