### ISSUE TITLE
TypeError: convert_json() takes at least 3 arguments (2 given)

### ISSUE THREAD

**Issue by naveenarumugam** [andrewgross/json2parquet#21]
>>> convert_json('~/hl/projects/json2parquet/json_sample_01.json', '~/hl/projects/json2parquet/json_sample_01.parq')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: convert_json() takes at least 3 arguments (2 given)

Seems to be documentation error

**Comment by andrewgross** [comment]
Thanks, I will update the signatures.

**Comment by andrewgross** [comment]
Fixed in `0.0.18`
