### ISSUE TITLE
Upgrade pyarrow, or don't version lock it

### ISSUE THREAD

**Issue by zmjjmz** [andrewgross/json2parquet#37]
- I'm sure there's a good reason for the `pyarrow` version being fixed `0.14.0`, but the latest version of `pyarrow` is `1.0.1`
- There are a few bugs fixed since `0.14.0`
- I can try to do this myself (bump the version and run tests) but I'm filing this issue to make sure that PR would be merged if done

**Comment by andrewgross** [comment]
A PR would be great. Happy to merge it.

**Comment by andrewgross** [comment]
Thanks for the PR. Slightly modified it to lock just the major version for these packages below `2.0.0`. Released as `1.0.0`.
