### ISSUE TITLE
Add to conda

### ISSUE THREAD

**Issue by BastianZim** [andrewgross/json2parquet#39]
Hi,

thanks for creating this great package!

I was wondering if you would mind if I add this to [conda-forge](https://conda-forge.org) so that it can be downloaded using [conda](https://en.wikipedia.org/wiki/Conda_(package_manager))?

I could add you as maintainer to the feedstock, otherwise I'd keep an eye on it myself.

Thanks!

**Comment by andrewgross** [comment]
Feel free to add it to conda-forge for conda users.

Andrew Gross
andrew.w.gross@gmail.com

**Comment by BastianZim** [comment]
Awesome, will do. Is there a minimum python version I should specify? I couldn't find anything in _setup.py_.

**Comment by BastianZim** [comment]
Just to add, I did find a bound in the travis file 
https://github.com/andrewgross/json2parquet/blob/6d93556023ac3020704bef4bda93dbbd6c0afad8/.travis.yml#L5-L8

Should I use that?

**Comment by andrewgross** [comment]
You can, I think it should be fine with Python3 >= 3.5, I just haven't updated in a while. My main concern is the dependent pyarrow/arrow libs not being supported by older python eventually, but we can cross that bridge when we come to it.

**Comment by BastianZim** [comment]
Ok, sounds good. I double-checked with conda-forge, and their minimum supported version is 3.6, so I now created the recipe with that, but that then shouldn't prevent a user from forking and changing the feedstock repo.

**Comment by BastianZim** [comment]
Also, the feedstock repo is now created and available here: https://github.com/conda-forge/json2parquet-feedstock

if you'd like to be added as a maintainer or if you would like me to add this to the download section in the Readme here, feel free to just ping me.

**Comment by andrewgross** [comment]
Adding it to the README in a PR would be awesome, thanks!

Andrew Gross
andrew.w.gross@gmail.com
